[package]
name = "on_chain_radio"
version = "1.0.0"
authors = []

[addresses]
addr_on_chain_radio = "9f5a1acdaeb54a53e78b5fe9f1045884145da9ed850016d8c2a4806ffb1532bf"
admin = "d0acc1f7cee58e2fdb626ffb93e50c6aa11d0284b37559f630a207ec2ab77f01"
addr_res_acc_ocr = "0x277552fcd88b668b24181051afad4f78efbb23ac20e3533becb1babe444fd0fe"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
